version: '3.1'

services :
  app:
    image: mispon/digi-express:latest
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - html:/app/html
    depends_on:
      - db
    links:
      - db:database
    environment:
      SELLER_ID: ${SELLER_ID}
      SELLER_API_KEY: ${SELLER_API_KEY}
      DATABASE_URL: postgres://${PG_USER}:${PG_PASS}@database:5432/digi
      TG_USER: ${TG_USER}

  db:
    image: postgres:15.2-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: digi

  admin:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8082:8080"

volumes:
  html:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './html'
  dbdata:
    driver: local