version: '3.1'

services :
  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "84:8080"

volumes:
  dbdata:
    driver: local