version: '3.1'

services :
  app:
    image: mispon/digi-express:v1.0.0
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db:database
    environment:
      SELLER_ID: your_seller_id
      SELLER_API_KEY: your_seller_api_key
      DATABASE_URL: postgres://admin:admin@database:5432/digi

  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: digi

  admin:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8082:8080"

volumes:
  dbdata:
    driver: local