name: digi-express-gists
on: [push]
jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-readme
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/5305767788b6bae4629e8f6aefc5e10a
          gist_title: digi-express.md
          gist_description: ""
          github_file: README.md

      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-install-script
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/0bb9127090d597d1d0c72beb0d45815c
          gist_title: install.sh
          gist_description: ""
          github_file: scripts/install.sh

      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-compose
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/8613e6a133d2eab625c60ffcf70c9e9c
          gist_title: docker-compose.yaml
          gist_description: ""
          github_file: docker-compose.yaml
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-sql-script
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/8613e6a133d2eab625c60ffcf70c9e9c
          gist_title: create_tables.sql
          gist_description: ""
          github_file: create_tables.sql
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-run-script
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/8613e6a133d2eab625c60ffcf70c9e9c
          gist_title: run.sh
          gist_description: ""
          github_file: scripts/run.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-update-script
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/8613e6a133d2eab625c60ffcf70c9e9c
          gist_title: update.sh
          gist_description: ""
          github_file: scripts/update.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-repair-script
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/8613e6a133d2eab625c60ffcf70c9e9c
          gist_title: repair.sh
          gist_description: ""
          github_file: scripts/repair.sh
