name: digi-express-gists
on: [push]
jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/5305767788b6bae4629e8f6aefc5e10a
          gist_title: digi-express.md
          gist_description: ""
          github_file: README.md
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/mispon/8613e6a133d2eab625c60ffcf70c9e9c
          gist_title: docker-compose.yaml
          gist_description: ""
          github_file: docker-compose.yaml
